packages: []

catalogs:
  bun:
    bun-git-hooks: ^0.1.0
    bun-plugin-auto-imports: ^0.3.1
    bun-plugin-dotenvx: ^0.6.3
    bun-plugin-dtsx: ^0.21.9
    bun-plugin-unocss: ^0.1.2

  core:
    '@stacksjs/actions': ^0.70.9
    '@stacksjs/ai': ^0.70.9
    '@stacksjs/alias': ^0.70.9
    '@stacksjs/analytics': ^0.70.9
    '@stacksjs/api': ^0.70.9
    '@stacksjs/arrays': ^0.70.9
    '@stacksjs/audiox': ^0.1.1
    '@stacksjs/auth': ^0.70.9
    '@stacksjs/browser': ^0.70.9
    '@stacksjs/buddy': ^0.70.9
    '@stacksjs/build': ^0.70.9
    '@stacksjs/cache': ^0.70.9
    '@stacksjs/calendar-api': ^0.70.9
    '@stacksjs/chat': ^0.70.9
    '@stacksjs/clarity': ^0.2.0
    '@stacksjs/cli': ^0.70.9
    '@stacksjs/cloud': ^0.70.9
    '@stacksjs/collections': ^0.70.9
    '@stacksjs/config': ^0.70.9
    '@stacksjs/database': ^0.70.9
    '@stacksjs/datetime': ^0.70.9
    '@stacksjs/desktop': ^0.70.9
    '@stacksjs/development': ^0.70.9
    '@stacksjs/dns': ^0.70.9
    '@stacksjs/dnsx': ^0.2.2
    '@stacksjs/docs': ^0.70.9
    '@stacksjs/dtsx': ^0.8.0
    '@stacksjs/email': ^0.70.9
    '@stacksjs/enums': ^0.70.9
    '@stacksjs/env': ^0.70.9
    '@stacksjs/error-handling': ^0.70.9
    '@stacksjs/events': ^0.70.9
    '@stacksjs/faker': ^0.70.9
    '@stacksjs/git': ^0.70.9
    '@stacksjs/health': ^0.70.9
    '@stacksjs/http': ^0.70.9
    '@stacksjs/httx': ^0.1.5
    '@stacksjs/lint': ^0.70.9
    '@stacksjs/logging': ^0.70.9
    '@stacksjs/notifications': ^0.70.9
    '@stacksjs/objects': ^0.70.9
    '@stacksjs/orm': ^0.70.9
    '@stacksjs/path': ^0.70.9
    '@stacksjs/payments': ^0.70.9
    '@stacksjs/push': ^0.70.9
    '@stacksjs/qrx': ^0.1.0
    '@stacksjs/query-builder': ^0.70.9
    '@stacksjs/queue': ^0.70.9
    '@stacksjs/realtime': ^0.70.9
    '@stacksjs/registry': ^0.70.9
    '@stacksjs/repl': ^0.70.9
    '@stacksjs/router': ^0.70.9
    '@stacksjs/rpx': ^0.10.0
    '@stacksjs/scheduler': ^0.70.9
    '@stacksjs/search-engine': ^0.70.9
    '@stacksjs/security': ^0.70.9
    '@stacksjs/server': ^0.70.9
    '@stacksjs/shell': ^0.70.9
    '@stacksjs/slug': ^0.70.9
    '@stacksjs/sms': ^0.70.9
    '@stacksjs/storage': ^0.70.9
    '@stacksjs/strings': ^0.70.9
    '@stacksjs/testing': ^0.70.9
    '@stacksjs/tinker': ^0.70.9
    '@stacksjs/tlsx': ^0.10.0
    '@stacksjs/tunnel': ^0.70.9
    '@stacksjs/types': ^0.70.9
    '@stacksjs/ui': ^0.70.9
    '@stacksjs/utils': ^0.70.9
    '@stacksjs/validation': ^0.70.9
    '@stacksjs/whois': ^0.70.9
    '@stacksjs/x-ray': ^0.70.9

  eslint:
    '@stacksjs/eslint-config': ^4.10.2-beta.3

  libs:
    jpgx: ^0.2.0
    localtunnels: ^0.1.1
    pngx: ^0.1.1
    ts-collect: ^0.4.0
    ts-gif: ^0.1.2
    ts-ndarray: ^0.1.0
    ts-spreadsheets: ^0.2.0

  unrelated:
    '@types/node': ^22.13.11
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    netlify-plugin-cache: ^1.0.3
    node-modules-inspector: ^0.5.7
    pnpm: ^10.6.5
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.2

  vite:
    '@stacksjs/vite-config': ^0.70.9
    '@stacksjs/vite-plugin': ^0.70.9
    vite-plugin-dotenvx: ^0.1.1
    vite-plugin-local: ^0.5.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
